### PR TITLE
added kwargs to each function

### PR DESCRIPTION
**Pull request by StephenCoady**
solves: #38 

Signed-off-by: Stephen Coady <scoady@redhat.com>

### CODE REVIEW

**Comment by livenson** [comment]
Could you please also regenerate the client within this PR?

**Comment by StephenCoady** [comment]
haha woops. forgot to `git add` it :man_shrugging:

**Comment by livenson** [comment]
Thank you! Do you need a release?

**Comment by StephenCoady** [comment]
@livenson yeah that would be great if its not too much trouble!

**Comment by livenson** [comment]
Done, 1.0.5

**Pull request merged**
