### PR TITLE
removing bad param causing service_add to fail

### PR DESCRIPTION
**Pull request by julianbarnett**
service_add fails with "Unknown option: skip_host_check". Removing this line as it seems to be unneeded.

### CODE REVIEW

**Comment by AmbientLighter** [comment]
Meta client is generated automatically from API metadata, therefore this change would be overidden next time when client is updated. I suppose that the root cause of this issue is version mismatch. Therefore could you please check which API version are you actually using? Please note that server version is not the same as  API version.

**Comment by julianbarnett** [comment]
'version': '4.6.4'
'api_version': '2.230'

I think the main issue here (and my PR will need to be updated) is that the skip_host_check param needs to only exist for server versions 4.7+, which I'm not on thus the confusion why it was there.

**Comment by julianbarnett** [comment]
@AmbientLighter I've updated my PR. This should fix the issue for all versions.

**Comment by AmbientLighter** [comment]
Thanks for update. But this code is going to be overridden as well. Therefore it makes sense to regenerate client using your actual FreeIPA server as it is described in our documentation or update your FreeIPA server to the newer release. Currently we don't support older FreeIPA releases.

**Comment by AmbientLighter** [comment]
See also https://python-freeipa.readthedocs.io/en/latest/#recreation-of-metaclient

**Comment by AmbientLighter** [comment]
Another option is to  override method in question in the new class inherited from base client class.

**Pull request closed without merging**
